### PR TITLE
Updated HardDrive.icns to correctly sized Big Sur Icon

### PR DESCRIPTION
**Pull request by R-Teer**
Should fix the issue with the Hard Drive Icon 👍🏼

### CODE REVIEW

**Comment by profzei** [comment]
Hi @R-Teer 
I've seen your message on reddit chat. In the following you find my stripped version for `AirportItlwm.kext`:
[AirportItlwm.kext.zip](https://github.com/profzei/Matebook-X-Pro-2018/files/5528755/AirportItlwm.kext.zip)
Let me know if you'll fix your  issue...

**Comment by R-Teer** [comment]
Hi @profzei, just tried the kext you posted, no success on my end unfortunatly so reverting back to heliport and itlwm.kext

How is OC 0.6.3 working for you, do we need to build a new config.plist or just use the one from 0.6.2.

Can confirm that public release of big sur is working great, just updated this morning on 0.6.2

**Comment by profzei** [comment]
Hi @R-Teer , have you tried using AirportItlwm on Big Sur or Catalina? There are different versions of the same kext to be loaded and probably a different setting specific for Big Sur (but atm I don't remember well...)

I didn't share the actual config.plist for OC 0.6.3 because I'm still working on it... I'd like to share a new release in a few days probably during weekend

I'm tempted to update to Big Sur following your feedback...

**Comment by profzei** [comment]
Hi @R-Teer 
sorry bothering you... but I'd like your feedback. I'm using OC 0.6.4 debug version for my tests and I found these missing icons alerts for your amazing theme:
```
06:444 00:016 OCUI: Failed to load image (2/2) Resources\Image\ExtApple.icns old:0 icon:1 - Not Found
06:461 00:016 OCUI: Failed to load image (2/2) Resources\Image\ExtWindows.icns old:0 icon:1 - Not Found
06:462 00:000 OCUI: Failed to load image (1/2) Resources\Image\Other.icns old:0 icon:1 - Not Found
06:466 00:004 OCUI: Failed to load image (2/2) Resources\Image\ExtTool.icns old:0 icon:1 - Not Found
06:470 00:004 OCUI: Failed to load image (2/2) Resources\Image\ExtResetNVRAM.icns old:0 icon:1 - Not Found
06:474 00:004 OCUI: Failed to load image (2/2) Resources\Image\ExtShell.icns old:0 icon:1 - Not Found
```

As you know your theme is working great, but I'd like to know if your had consistent icons or not...
Thank you,
R

**Pull request merged**
