### PR TITLE
Custom Opencanopy Configuration

### PR DESCRIPTION
**Pull request by R-Teer**
Ive put together a cleaner version of Opencanopy with custom graphics

This can be enabled by configuring the config.plist

`Misc -> Boot -> PickerMode: External`
`Misc -> Boot -> PickerAttributes:1`

I personally use hide auxiliary also (can be viewed using spacebar during picker screen)

I have built graphics that work perfectly with our display, along with better icon spacing and readability.

Added new T2 chip boot chime, with better bass and key change from legacy chime

Also, optimised image file sizes for some resources

### CODE REVIEW

**Comment by R-Teer** [comment]
IMG_20201105_150009

IMG_20201105_145949

**Comment by profzei** [comment]
@R-Teer :  Great work! Thank you very much for your contribution!

**Comment by profzei** [comment]
@R-Teer : sorry but I'm not able to see **OpenCanopy GUI** at picker stage... I also added `OpenCanopy.efi` in `config.plist` in `Drivers` section...
Do you have any hints?

**Comment by profzei** [comment]
@R-Teer : Sorry! I resolved my issue! Thank you!

**Comment by R-Teer** [comment]
Yo Prof, sorry I missed your messages my man! Is everything working okay now?

**Comment by profzei** [comment]
@R-Teer Hi, now it's okay! I merged your awesome PR in my master branch...
In your commit `HardDrive.icns` was missing, so _OpenCanopy GUI_ didn't show up... I loaded the relative "standard" icon for `HardDrive.icns` in `Resources` folder... I don't know if it's needed to be replaced with a custom one (for internal coherence...)?
What do you think?

**Comment by R-Teer** [comment]
Just took a look, it seems there was an issue on my end with the upload, seems to have been renamed to HardDrive2.icns

Ill make an adjustment now dude!

**Comment by R-Teer** [comment]
Just added new PR with the icons fixed!

**Pull request merged**
